import React, { useContext, useEffect, useState } from 'react'
import '../Css/dhruvin/Payment.css'
import { MdRefresh } from 'react-icons/md';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import noteContext from '../Context/noteContext';

const Payment = () => {

  const {Api ,store , setPayCount} = useContext(noteContext)
  const data = JSON.parse(localStorage.getItem("OrderDetails")) || {}
  const login = JSON.parse(localStorage.getItem("Login")) || {}
  const deliverId = JSON.parse(localStorage.getItem("default") || "")
  const [cardData, setCardData] = useState([])
  
  useEffect(()=>{
    window.scrollTo({ top: 0, behavior: 'smooth' });
  },[])

  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0'); 
  const day = String(today.getDate()).padStart(2, '0');

  const finalDate = `${year}-${month}-${day}`

  useEffect(()=>{
     axios.get(`${Api}/cart/getall`,{
      headers: {
        Authorization: `Bearer ${store?.access_token}`
      }
     }).then((value)=>{
        console.log(value?.data?.cart);
        setCardData(value?.data?.cart)
     }).catch((error)=>{
        alert("PaymentPage" , error)
     })
  },[])

  // const formattedProducts = cardData?.map((item) => ({
  //   product_id: item?.product_id,
  //   qty: item?.quantity,
  //   size: parseInt(item?.size ? item?.size : 2),
  //   metal: item?.metal,
  // }));

    // console.log("format " , formattedProducts);


  const handlePay = async () => {
      const formattedProducts = cardData?.map((item) => ({
        product_id: item?.product_id,
        qty: item?.quantity,
        size: parseInt(item?.size ? item?.size : 2),
        metal: item?.metal,
      }));


      console.log("xxxxxxxxxxxxxxxxxxxxxx " , formattedProducts);
      
      const directByNow = new Array(JSON.parse(localStorage.getItem("BuyNow"))) || null
      console.log("directByNow " , directByNow);
      
      const byNowProducts = directByNow.map((item)=>({
        product_id: item?.product_id,
        qty: item?.qty,
        size: parseInt(item?.size ? item?.size : 2),
        metal: item?.metal,
      }))
      
    
      const maxRetries = 3; 
      const retryDelay = (retryCount) => Math.pow(2, retryCount) * 1000; 
      // console.log("fwebnfghweifhwei " , directByNow);
      
    
      const createOrder = async (retryCount = 0) => {
        try {
          const response = await axios.post(
            `${Api}/order/create`,
            {
              customer_id: login?.id,
              order_date: finalDate,
              order_status: 'pending',
              total_amount: data?.total,
              deliveryAddress_id: deliverId,
              discount: data?.discount ? data?.discount : 0,
              products: !directByNow === null ? byNowProducts : formattedProducts,
            },
            {
              headers: {
                Authorization: `Bearer ${store?.access_token}`,
              },
            }
          );
          alert("Payment SuccessFully")
          localStorage.setItem("orderId", JSON.stringify(response?.data?.order?.order_id));
          if(response?.data?.order){
            console.log('order',response?.data?.order); 
            // removeCartItem();
          }
          // navigate("/orderdetails");
        } catch (error) {
          if (error.response?.status === 429 && retryCount < maxRetries) {
            console.warn(`Retrying order creation in ${retryDelay(retryCount)}ms...`);
            await new Promise((resolve) => setTimeout(resolve, retryDelay(retryCount)));
            return createOrder(retryCount + 1);
          }
    
          console.error("Error creating order:", error);
          alert(`Error: ${error.response?.data?.message || error.message}`);
        }
      };
    
      await createOrder();
      
      
      setPayCount((payCount)=> payCount + 1)
  };


  // *************** Razorpay **************
  
  const handlePayment = async () => {
    const response = await fetch("http://localhost:5000/create-order", { method: "POST" });
    const orderData = await response.json();

    const options = {
      key: "YOUR_RAZORPAY_KEY_ID", // Replace with your Razorpay key
      amount: orderData.amount,
      currency: orderData.currency,
      name: "Your Company Name",
      description: "Test Transaction",
      image: "https://yourlogo.com/logo.png", // Optional
      order_id: orderData.id, // Order ID generated by your server
      handler: (response) => {
        console.log(response);
        alert("Payment Successful!");
      },
      prefill: {
        name: "John Doe",
        email: "john.doe@example.com",
        contact: "9999999999",
      },
      notes: {
        address: "Your Company Address",
      },
      theme: {
        color: "#3399cc",
      },
    };

    const rzp1 = new window.Razorpay(options);
    rzp1.open();
  };
  

  return (
    <>
      <section className='mb-5 pb-4 ds_cart-main'>
        <div className='ds_container'>
          <h2>Cart</h2>
           <div className="row">
             <div className="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12 ">
             <div className="ds_cod-main mt-sm-5 mt-4 ds_cod-bg">
                      <div className="row p-0 m-0" style={{ borderBottom: '1px solid black' }}>
                          <div className="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center p-0">
                            <button  className={` h-100  ds_cod-on-btn`} >
                              Pay On Delivery
                            </button>
                          </div>
                      </div>
                        <section className="ds_pay-box mt-sm-4">
                          <div className="row justify-content-center mx-xl-0 mx-2">
                            <div className="col-xl-8">
                              <div className="row">
                                <div className="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12 mt-3"></div>
                                <div className="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12 mt-3">
                                  <p className="ds_pay-text ds_tcolor mb-0">Enter the captcha to confirm order.</p>
                                </div>
                              </div>

                              <div className="row justify-content-center align-items-center">
                                <div className="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12 mt-3">
                                  <img src={require("../Img/dhruvin/captha.png")} alt="" className="ds_cod-cap" />
                                </div>
                                <div className="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12 mt-3">
                                  <input type="text" className="ds_cod-input" placeholder="Enter the captcha" />
                                </div>
                                <div className="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-12 mt-3">
                                  <MdRefresh className="ds_cod-refresh" />
                                </div>
                              </div>

                              <div className="row mt-sm-4 pt-2 mt-3">
                                <div className="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12"></div>
                                <div className="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12">
                                  <button className=" ds_cod-pay" onClick={handlePay} >Pay ₹ {data?.total}</button>
                                </div>
                              </div>

                              <div className="row mt-sm-4 pt-2 mt-3">
                                <div className="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12"></div>
                                <div className="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12 text-center">
                                    <span className='text-muted'>Or</span>
                                </div>
                              </div>


                              <div>
                                <div className="row mt-sm-4 mt-3">
                                  <div className="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12"></div>
                                  <div className="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12">
                                     <button onClick={handlePayment} className="ds_cod-razo ds_color fw-bold" >Pay with <img src={require("../Img/dhruvin/razor.png")} alt="" width="25%" /> </button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                     

                     


                    </div>
             </div>
             <div className="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12 mt-5">
                <div>
                <div className="ds_add-order ">
                     <div>
                       <h6 className="h6 ms-3 fw-600 mb-3 ds_color">
                         Order Details
                       </h6>
                       <div className="ds_with-border"></div>
                     </div>
                     <div className="px-3 mt-3">
                       <div className="d-flex justify-content-between">
                         <p className="ds_tcolor">Sub Total</p>
                         <p className="fw-600 ds_color ds_600">₹{data?.sub_total}</p>
                       </div>
                       <div className="d-flex justify-content-between">
                         <p className="ds_tcolor">Discount</p>
                         <p className="fw-600 ds_add-color ds_600">-₹{data?.discount}</p>
                       </div>
                       <div className="d-flex justify-content-between">
                         <p className="ds_tcolor">Tax</p>
                         <p className="fw-600 ds_color ds_600">₹{data?.tax}</p>
                       </div>
                       <div className="d-flex justify-content-between">
                         <p className="ds_tcolor">Delivery Charge</p>
                         <p className="fw-600 ds_add-color ds_600">FREE</p>
                       </div>
                     </div>
                     <div className="ds_with-border mt-2"></div>
                     <div className="px-3 mt-3">
                       <div className="d-flex justify-content-between">
                         <h5 className="h5 mb-0 ds_color">Total Amount</h5>
                         <h5 className="h5 mb-0 ds_color">₹{data?.total}</h5>
                       </div>
                     </div>
                </div>
                </div>
             </div>
           </div>
        </div>
      </section>
    </>
  )
}

export default Payment
